name: Docker Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and push Docker image
      env:
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
        DOCKER_TAG: ${{ secrets.DOCKER_TAG }}
      run: |
        docker build --platform linux/arm64 --no-cache -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_TAG .
        docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_TAG

    - name: Deploy with Docker Compose
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_SERVER: ${{ secrets.REMOTE_SERVER }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        DOCKER_REGISTRY_LOCAL: ${{ secrets.DOCKER_REGISTRY_LOCAL }}
        DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
        DOCKER_TAG: ${{ secrets.DOCKER_TAG }}
        COMPOSE_FILE_PATH: ${{ secrets.COMPOSE_FILE_PATH }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p $SSH_PORT $REMOTE_USER@$REMOTE_SERVER "docker pull $DOCKER_REGISTRY_LOCAL/$DOCKER_IMAGE_NAME:$DOCKER_TAG"
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p $SSH_PORT $REMOTE_USER@$REMOTE_SERVER "docker compose -f $COMPOSE_FILE_PATH down && docker compose -f $COMPOSE_FILE_PATH pull && docker compose -f $COMPOSE_FILE_PATH up -d"
